### PR TITLE
Starts QCFractal Integration Testing

### PR DESCRIPTION
**Pull request by dgasmith**
## Description
 - Switches testing constructs over to QCF* type via conda-envs which the cookie cutter will likely migrate too as well.
 - Adds QCFractal and depends testing, explicitly pulls many QCF dependencies from `conda` rather than accidentals via pip. This will be greatly simplified once we push Fractal out to Conda-forge or similar.
 - Pulls tagged geometric/torsiondrives for testing.
 - Adds a quick torsion drive test case.

## Status
- [ ] Ready to go

### CODE REVIEW

**Comment by ChayaSt** [comment]
The OSX build is passing now because the qcfractal test is skipped. It fails on the Linux build because `hooh.json` is not found. I'll raise an issue on qcfracal.

**Comment by dgasmith** [comment]
Found it, if you check the logs now you will see that we messed up the OpenEye license files somehow. I think they call straight `exit(1)` which we should probably ask them to raise an error instead. `exit` is bad practice as it leads to issue like above where the program just stops with no further output or information beyond to `stdout/stderr` which in this case pytest was capturing.

**Comment by ChayaSt** [comment]
@dgasmith, the reason why the builds are failing is right here:
https://travis-ci.org/openforcefield/fragmenter/jobs/455768820#L180
The license does not get installed in forks. I will open a separate PR but in the future if you want to make any changes directly, open a branch from this repo.

**Comment by dgasmith** [comment]
Great, glad you got this fixed and good to see the testing merged!

**Comment by jchodera** [comment]
> Found it, if you check the logs now you will see that we messed up the OpenEye license files somehow. I think they call straight exit(1) which we should probably ask them to raise an error instead. exit is bad practice as it leads to issue like above where the program just stops with no further output or information beyond to stdout/stderr which in this case pytest was capturing.

This behavior is intentional (if annoying!), and they expect users to check if the software is licensed first with [`OE*IsLicensed`](https://docs.eyesopen.com/toolkits/python/releasenotes/releasenotes1_7_4.html) calls.

**Pull request merged**
